//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTester.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ================================= 的本地化字符串。
        /// </summary>
        internal static string DefaultSeparator {
            get {
                return ResourceManager.GetString("DefaultSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untitled 的本地化字符串。
        /// </summary>
        internal static string DefaultUntitledString {
            get {
                return ResourceManager.GetString("DefaultUntitledString", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Operation &quot;{0}&quot; Working... 的本地化字符串。
        /// </summary>
        internal static string DoBackgroundWorkProgressTextFormat {
            get {
                return ResourceManager.GetString("DoBackgroundWorkProgressTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clearing Result Nodes... 的本地化字符串。
        /// </summary>
        internal static string DoClearNodeBackgroundWorkProgressText {
            get {
                return ResourceManager.GetString("DoClearNodeBackgroundWorkProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting Report...{0}% 的本地化字符串。
        /// </summary>
        internal static string DoExportBackgroundWorkProgressTextFormat {
            get {
                return ResourceManager.GetString("DoExportBackgroundWorkProgressTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Importing Report...{0}% 的本地化字符串。
        /// </summary>
        internal static string DoImportBackgroundWorkProgressTextFormat {
            get {
                return ResourceManager.GetString("DoImportBackgroundWorkProgressTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding Result Nodes...{0}% 的本地化字符串。
        /// </summary>
        internal static string DoResultBackgroundWorkProgressTextFormat {
            get {
                return ResourceManager.GetString("DoResultBackgroundWorkProgressTextFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 An exception occurred. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageBoxExceptionOccuredText {
            get {
                return ResourceManager.GetString("ExceptionMessageBoxExceptionOccuredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InnerException: 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageBoxInnerExceptionOccuredText {
            get {
                return ResourceManager.GetString("ExceptionMessageBoxInnerExceptionOccuredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1}{0}{0}{2} 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageBoxStructureFormat {
            get {
                return ResourceManager.GetString("ExceptionMessageBoxStructureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1}{0}{3}{0}{2}{0}{3} 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageBoxTextFormat {
            get {
                return ResourceManager.GetString("ExceptionMessageBoxTextFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Edit {0} 的本地化字符串。
        /// </summary>
        internal static string PatternEditDialogTitleFormat {
            get {
                return ResourceManager.GetString("PatternEditDialogTitleFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Regex {
            get {
                object obj = ResourceManager.GetObject("Regex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Regular Expression Pattern 的本地化字符串。
        /// </summary>
        internal static string RegexPatternEditTag {
            get {
                return ResourceManager.GetString("RegexPatternEditTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following patterns cannot be empty:{0}Regular Expression Pattern 的本地化字符串。
        /// </summary>
        internal static string RegexPatternEmptyExceptionMessageFormat {
            get {
                return ResourceManager.GetString("RegexPatternEmptyExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replacement Pattern 的本地化字符串。
        /// </summary>
        internal static string ReplacePatternEditTag {
            get {
                return ResourceManager.GetString("ReplacePatternEditTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Built on {0} 的本地化字符串。
        /// </summary>
        internal static string ReportBuiltTimeStringFormat {
            get {
                return ResourceManager.GetString("ReportBuiltTimeStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Report 的本地化字符串。
        /// </summary>
        internal static string ReportExportFileDialogTitle {
            get {
                return ResourceManager.GetString("ReportExportFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegexTester Log (*.log)|*.log|Text Document (*.txt)|*.txt|All Files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string ReportFileDialogFilter {
            get {
                return ResourceManager.GetString("ReportFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegexTester_Report_{0} 的本地化字符串。
        /// </summary>
        internal static string ReportFileNameFormat {
            get {
                return ResourceManager.GetString("ReportFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import from Report 的本地化字符串。
        /// </summary>
        internal static string ReportImportFileDialogTitle {
            get {
                return ResourceManager.GetString("ReportImportFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matched on {0} 的本地化字符串。
        /// </summary>
        internal static string ReportMatchTimeStringFormat {
            get {
                return ResourceManager.GetString("ReportMatchTimeStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Result 的本地化字符串。
        /// </summary>
        internal static string ReportNoResultText {
            get {
                return ResourceManager.GetString("ReportNoResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegexTester Report (*.log, *.txt)|*.log;*.txt 的本地化字符串。
        /// </summary>
        internal static string ReportOpenFileDialogFirstFilter {
            get {
                return ResourceManager.GetString("ReportOpenFileDialogFirstFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegexOptions 的本地化字符串。
        /// </summary>
        internal static string ReportOptionsTitle {
            get {
                return ResourceManager.GetString("ReportOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regular Expression 的本地化字符串。
        /// </summary>
        internal static string ReportPatternTitle {
            get {
                return ResourceManager.GetString("ReportPatternTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result (Count: {0}) 的本地化字符串。
        /// </summary>
        internal static string ReportResultTitleFormat {
            get {
                return ResourceManager.GetString("ReportResultTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string ReportTextTitle {
            get {
                return ResourceManager.GetString("ReportTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ticks ({1} ns) 的本地化字符串。
        /// </summary>
        internal static string ReportTickTextFormat {
            get {
                return ResourceManager.GetString("ReportTickTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version {0} 的本地化字符串。
        /// </summary>
        internal static string ReportVersionStringFormat {
            get {
                return ResourceManager.GetString("ReportVersionStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        internal static string ResultFormDefaultTitle {
            get {
                return ResourceManager.GetString("ResultFormDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result - Count: {0} | Time: {1} 的本地化字符串。
        /// </summary>
        internal static string ResultFormTitleFormat {
            get {
                return ResourceManager.GetString("ResultFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; at index {1} 的本地化字符串。
        /// </summary>
        internal static string ResultNodeTextFormat {
            get {
                return ResourceManager.GetString("ResultNodeTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To keep consistency, old results have been removed. 的本地化字符串。
        /// </summary>
        internal static string ResultRemovedToolTipText {
            get {
                return ResourceManager.GetString("ResultRemovedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Old results has been removed 的本地化字符串。
        /// </summary>
        internal static string ResultRemovedToolTipTitle {
            get {
                return ResourceManager.GetString("ResultRemovedToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running Time Measurement 的本地化字符串。
        /// </summary>
        internal static string RunningTimeMeasurementOperationText {
            get {
                return ResourceManager.GetString("RunningTimeMeasurementOperationText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Select {
            get {
                object obj = ResourceManager.GetObject("Select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 High-Resolution Performance Counter 的本地化字符串。
        /// </summary>
        internal static string StopwatchHighResolutionCounterText {
            get {
                return ResourceManager.GetString("StopwatchHighResolutionCounterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Timer (System.DateTime) 的本地化字符串。
        /// </summary>
        internal static string StopwatchSystemTimerText {
            get {
                return ResourceManager.GetString("StopwatchSystemTimerText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Style {
            get {
                object obj = ResourceManager.GetObject("Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Text Document (*.txt)|*.txt|All Files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string TextDocumentFileDialogFilter {
            get {
                return ResourceManager.GetString("TextDocumentFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - Text 的本地化字符串。
        /// </summary>
        internal static string TextFormTitleFormat {
            get {
                return ResourceManager.GetString("TextFormTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Time: {0} ns 的本地化字符串。
        /// </summary>
        internal static string TickButtonTextFormat {
            get {
                return ResourceManager.GetString("TickButtonTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The amount of time for Regular Expression pattern {1}{1} &quot;{0}&quot; {1}{1} = {2} ticks ({3} ns) {1}{1} {4} {1} Baseline Parameters: {1}{1} Method: System.Diagnostics.Stopwatch {1} Frequency: {5} ticks / second ({6} ns / tick) {1} Based on {7}{1}{4} 的本地化字符串。
        /// </summary>
        internal static string TickInfoMessageBoxTextFormat {
            get {
                return ResourceManager.GetString("TickInfoMessageBoxTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average Time: {0} ticks ({1} ns) 的本地化字符串。
        /// </summary>
        internal static string TickInfoMessageBoxTitleFormat {
            get {
                return ResourceManager.GetString("TickInfoMessageBoxTitleFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WordWarp {
            get {
                object obj = ResourceManager.GetObject("WordWarp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
